# This file is for Shopify employees development environment.
# If you are an external contributor you don't have to bother with it.
name: ci-queue

up:
  - python: 3.10.11
  - custom:
      name: "link development ci-queue as a package"
      met?: "pip show ciqueue | grep -i \"Location: $(pwd)\""
      meet: "make install"
  - railgun

commands:
  test: make test
