name: Tests

on: [push, pull_request]

jobs:
  ruby-tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3.0'
          - 'truffleruby'
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo apt-get install libsnappy-dev
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Run Ruby tests
        run: |
          bin/before-install
          bin/test
        env:
          SUITE: ruby
          REDIS_HOST: localhost

  python-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python: [ '3.7.17', '3.8.1', '3.9.23', '3.10.18', '3.11.13' ]

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Run Python tests
        run: |
          bin/before-install
          bin/test
        env:
          SUITE: python
          PYTHON_VERSION: ${{ matrix.python }}
          REDIS_HOST: localhost
          REDIS_PORT: 6379
