name: Tests

on: [push]

jobs:
  ruby-tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.7', '3.0', '3.1', '3.2' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Run Ruby tests
        run: |
          bin/before-install
          bin/test
        env:
          SUITE: ruby
          REDIS_HOST: localhost

  python-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2
      - name: Install Python 2.7, 3.6, 3.7
        run: |
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt-get -qq update
          sudo apt-get install -y python2.7 python3.6 python3.7
          # https://github.com/pypa/setuptools/issues/2988#issuecomment-1007991935
          git clone https://github.com/pypa/setuptools.git && cd setuptools && sudo python3.10 setup.py install
          sudo apt install python3.10-distutils
          curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
          sudo apt install python3.10-venv
          sudo pip install autopep8
      - name: Run Python tests
        run: |
          bin/before-install
          bin/test
        env:
          SUITE: python
          REDIS_HOST: localhost
          REDIS_PORT: 6379
