name: Tests

on: [push]

jobs:
  ruby-tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - 'truffleruby'
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo apt-get install libsnappy-dev
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Run Ruby tests
        run: |
          bin/before-install
          bin/test
        env:
          SUITE: ruby
          REDIS_URL: redis://localhost:6379/0

  python-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python: [ '3.7', '3.8', '3.9', '3.10', '3.11' ]

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2
      - name: Install Python ${{ matrix.python }}
        run: |
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt-get -qq update
          sudo apt-get install -y python${{ matrix.python }} python${{ matrix.python }}-distutils
          sudo pip install autopep8
      - name: Run Python tests
        run: |
          bin/before-install
          bin/test
        env:
          SUITE: python
          PYTHON_VERSION: ${{ matrix.python }}
          REDIS_URL: redis://localhost:6379/0
